import Navbar from "../components/navbar/navbar";
import "./globals.css";
import ThemeProvider from "../components/ui/theme-provider";
import { BasketProvider } from "../store/basketStore";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="flex flex-col h-screen">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <BasketProvider>
            <Navbar />
            {children}
          </BasketProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
